easy_admin:
    site_name: 'Administration'
    design:
        brand_color: '#b43c3c'
        assets:
            favicon: '/images/favicon.png'
        menu:
            - { label: 'Homepage', route: 'homepage', icon: 'home' }
            - { entity: 'Content', label: 'Contents', icon: 'file-text' }
            - { entity: 'Project', label: 'Projects', icon: 'briefcase' }
            - label: 'Skills'
              icon: 'graduation-cap'
              children:
                - { entity: 'SkillGroup', label: 'Groups'}
                - { entity: 'SkillItem', label: 'Items' }
            - { entity: 'Social', label: 'Socials', icon: 'share-square' }
            - { entity: 'Message', label: 'Messages', icon: 'envelope' }

imports:
    - { resource: easy_admin_entities/ }
