vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: '%app.path.projects_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.projects_images%'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'titleEn'}

        skill_image:
            uri_prefix: '%app.path.skills_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.skills_images%'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'titleEn'}
