vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'titleEn'}

        skill_image:
            uri_prefix: /images/skills
            upload_destination: '%kernel.project_dir%/public/images/skills'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'titleEn'}
