easy_admin:
    entities:
        Message:
            class: App\Entity\Message
            disabled_actions: ['edit']
            list:
                sort: sentAt
                actions: ['show']
                fields:
                    - name
                    - email
                    - subject
                    - sentAt
            show:
                fields:
                    - name
                    - { property: email, type: email }
                    - subject
                    - message
                    - sentAt
