easy_admin:
    entities:
        SkillItem:
            class: App\Entity\SkillItem
            list:
                sort: skillGroup
                fields:
                    - skillGroup
                    - position
                    - titleEn
                    - titleFr
                    - grade
                    - { property: imageName, type: image, base_path: '%app.path.skills_images%' }
            form:
                fields:
                    - skillGroup
                    - titleEn
                    - titleFr
                    - grade
                    - position
                    - { property: imageFile, type: vich_image, base_path: '%app.path.skills_images%' }
