easy_admin:
    entities:
        SkillGroup:
            class: App\Entity\SkillGroup
            list:
                sort: position
                fields:
                    - position
                    - titleEn
                    - titleFr
                    - skillItems
            form:
                fields:
                    - titleEn
                    - titleFr
                    - position
